### PR TITLE
Edit pattern.md

### PR DESCRIPTION
**Pull request by jariji**
I made some edits to pattern.md. I filed some issues while I was going.

### CODE REVIEW

**Comment by thautwarm** [comment]
Will review this PR and #166 today.

**Review by thautwarm — APPROVED** [review]
Things look fine to me.

It seems you discard this:

> However, remember, due to some Julia optimization details, even if the guards can be put in the middle of a matching process, it is still better to postpone it until the end of matching sequence. This allows for better performance.

It's up to you whether to add the statement back. I haven't made any benchmark for the performance diff for a long time, but I do know a few cases that MLStyle's optimizations become meaningless in higher Julia version.

**Comment by thautwarm** [comment]
@jariji If you are ready for this PR to get merged, just mention me again.

**Comment by jariji** [comment]
@thautwarm I'm ready for this to be merged.

> It's up to you whether to add the statement back. I haven't made any benchmark for the performance diff for a long time, but I do know a few cases that MLStyle's optimizations become meaningless in higher Julia version.

I felt that the ordering optimization was too minor an issue to be raised in introductory docs.

**Pull request merged**
