### PR TITLE
Improved English

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Note, there was for sure at least one typo, but review my other suggestions. I'm neither a native English speaker. It just seems like your package is impressive, so I wanted to help a bit. Hopeully I didn't make the English worse or mess up e.g. newlines (wasn't sure about that part).

I tried to be conservative, I may have some rules wrong. E.g. wasn't sure if better:
"when they don't have pattern matching and ADTs," -> "or ADTs"?

**Comment by thautwarm** [comment]
Thanks a lot!
However the most places you modified are already refined by naive speakers...
I don't know how to make decisions for this, hence I'll ask my friends for dedicated help with wording/grammar stuffs...

**Comment by PallHaraldsson** [comment]
Feel free to wait. Most of the changes weren't to big of a deal, and I even made one type, now fixed.

Originally I saw yours "pattern mathing" (you could fix that or some other independently), and decided to fix and got carried away. The English wasn't bad at all. Some was just alternative style. I'm however pretty confident my version improves a bit, if something gets worse, a little more is for the better.

**Comment by thautwarm** [comment]
"pattern mathing"... That's a shame...
Thank you so much for your helps, indeed.

**Pull request merged**
